#! /usr/bin/env python

# Compares different setups for a simple script:
#
# - argparse
# - opto-py : usage text
# - opto-py : API
# - opto-py : simple spec + API

####
# argparse.
####

ap = argparse.ArgumentParser()
ap.add_argument('--since', type = int, default = 123)
ap.add_argument('--limit', type = int, default = 0)
ap.add_argument('--rebuild', action = 'store_true')
ap.add_argument('--experiment', action = 'store')
ap.add_argument('--stats', action = 'store_true')
ap.add_argument('--month')
ap.add_argument('--search', action = 'append')
ap.add_argument('--get')


####
# USAGE text.
####

USAGE = '''
    get-pocket-items [--limit N] [--rebuild] [--experiment EXP] [--stats]
                     [--month M] [--search TERM]... [--get ITEM]
    get-pocket-items [--help | -h] ...
'''

p = parser(
    usage = USAGE,
    opt('since', type = int, 'default' = 123),
    opt('since', type = int, 'default' = 0),
)


####
# opto-py : API.
####

p = parser(
    opt('--since TERM', type = int, default = 123),
    opt('--limit N', type = int, default = 0),
    opt('--rebuild'),
    opt('--experiment EXP'),
    opt('--stats'),
    opt('--month M'),
    opt('--search TERM', repeatable = True),
    opt('--get ITEM'),
)


####
# opto-py : API: simple spec.
####

spec = '--since TERM --limit N --rebuild --experiment EXP --status --month M --search TERM --get ITEM'
p = parser(simple = spec)
p.opt('since', type = int, default = 123)
p.opt('limit', type = int, default = 0)
p.opt('search', repeatable = True)

